config {
    type: "table",
    schema: "sf_traffic_gold",
    name: "dim_date",
    description: "Bảng Dimension Ngày (Trục thời gian dùng chung, tích hợp cờ Ngày lễ)",
    tags: ["gold", "dimension"],
    assertions: {
        uniqueKey: ["date_key"],
        nonNull: ["date_key", "full_date"]
    }
}

WITH date_spine AS (
    SELECT
        d AS full_date
    FROM
        UNNEST(GENERATE_DATE_ARRAY('2020-01-01', '2030-12-31', INTERVAL 1 DAY)) AS d
),
holiday AS (
    SELECT DISTINCT
        holiday_date,
        holiday_name
    FROM
        ${ref("slv_holiday")}
),
final AS (
    SELECT
        CAST(FORMAT_DATE('%Y%m%d', ds.full_date) AS INT64) AS date_key,
        ds.full_date,
        EXTRACT(YEAR FROM ds.full_date) AS year,
        EXTRACT(QUARTER FROM ds.full_date) AS quarter,
        EXTRACT(MONTH FROM ds.full_date) AS month,
        FORMAT_DATE('%B', ds.full_date) AS month_name,
        EXTRACT(WEEK FROM ds.full_date) AS week_of_year,
        EXTRACT(DAY FROM ds.full_date) AS day_of_month,
        EXTRACT(DAYOFYEAR FROM ds.full_date) AS day_of_year,
        EXTRACT(DAYOFWEEK FROM ds.full_date) AS day_of_week_num,
        FORMAT_DATE('%A', ds.full_date) AS day_name,
        CASE 
            WHEN EXTRACT(DAYOFWEEK FROM ds.full_date) IN (1, 7) THEN TRUE 
            ELSE FALSE 
        END AS is_weekend,
        CASE 
            WHEN h.holiday_date IS NOT NULL THEN TRUE 
            ELSE FALSE 
        END AS is_holiday,
        COALESCE(h.holiday_name, 'Not a Holiday') AS holiday_name
    FROM date_spine ds
    LEFT JOIN holiday h
        ON ds.full_date = h.holiday_date
)
SELECT * FROM final